### PR TITLE
Support continuous register mask for MatchField

### PR DESCRIPTION
**Pull request by commandgjj**
For NXReg, OvS will accept value/mask on arbitrary bitwise. If only using
range[start:end], it is hard to combine discontinuous value/mask,
such as, to merge reg0[0:0] with reg0[2:2], with range method,
we will pass NXRange[0:2] and it will generate mask 0x7, but actually,
the mask is 0x5.

In this patch, we add a new API (NewRegMatchFieldWithMask) to support
arbitrary bitwise mask for register value/mask.

Signed-off-by: Jinjun Gao <gjinjun@gmail.com>

### CODE REVIEW

**Comment by commandgjj** [comment]
Resolved VERSION conflict and mispell issue. But seems the new PR doesn't follow old PR thread.

**Comment by commandgjj** [comment]
> Resolved VERSION conflict and mispell issue. But seems the new PR doesn't follow old PR thread.

The old review thread: https://github.com/antrea-io/libOpenflow/pull/16

**Comment by commandgjj** [comment]
Hello, Wenying, do you have time to review this patch again? Thanks!

**Review by wenyingd — APPROVED** [review]
LGTM

**Review by tnqn — APPROVED** [review]
LGTM, thanks

**Pull request merged**
